### ISSUE TITLE
Warning in DevTools

### ISSUE THREAD

**Issue by sandor** [jarek-foksa/xel#28]
xel.min.html:1 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive.

Is this something I should worry about?

**Comment by jarek-foksa** [comment]
I can't mark all the "wheel" events as passive because I need to preventDefault() their default action which is scrolling a page. This might have negative performance impact on touch devices (mobile, tables), be shouldn't be a problem on desktop.

You should be able to hide those warning by switching the console display mode from "Verbose" to something lower:

![screenshot](https://user-images.githubusercontent.com/193371/27591468-0b4e7ee6-5b52-11e7-91cb-ebc623499e55.png)
