### ISSUE TITLE
Please compile the JavaScript on your website

### ISSUE THREAD

**Issue by tgdn** [jarek-foksa/xel#46]
Using classes and async on browsers that don't support it natively is not a good idea. However, your website's JS throws errors because it doesn't recognise what async means.

So impossible to see your website on Chrome because of:

`xel.min.js:764 Uncaught SyntaxError: Unexpected identifier`.

You should probably use something like Babel to compile your code.

[another issue that you closed but which is not fixed](https://github.com/jarek-foksa/xel/issues/36)

**Comment by jarek-foksa** [comment]
The current stable version of Chrome supports classes and async/await. You are right that the demo site should not be blank on older versions of Chrome. To fix it please make a pull request which adds additional checks for async/await and classes support [here](https://github.com/jarek-foksa/xel/blob/master/index.html#L39).

Personally, I don't care whether the site works on old Chrome versions as those have security vulnerabilities and should not be used in the first place.

Since the project targets only modern browsers and runtimes, compiling the code to older ES versions doesn't make much sense to me.
