### ISSUE TITLE
exclude xel-demo, xel-app from release

### ISSUE THREAD

**Issue by youngyou** [jarek-foksa/xel#96]
Exclude xel-demo, xel-app from release to make the bundle smaller. 
Also include src in release so we can import as we need.

**Comment by jarek-foksa** [comment]
I agree it doesn't make sense to include xel-demo and xel-app in the NPM package, though I would prefer to postpone this for now as I'm planning to do some major refactoring.

I would prefer to not include individual source files in the release because the minified single file version is already very small.

**Comment by jarek-foksa** [comment]
Done in Xel version 0.9.
